// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMfVD8KC5Y_bojCeuPza0nW645foWrANs',
    appId: '1:546106504523:android:3bf52f1c44dae253ae24ce',
    messagingSenderId: '546106504523',
    projectId: 'wasalni-68a0d',
    databaseURL: 'https://wasalni-68a0d-default-rtdb.firebaseio.com',
    storageBucket: 'wasalni-68a0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB17EqqxbWvu997_oIT1QGSfncMzs03DzY',
    appId: '1:546106504523:ios:d3c17a5117a63b5bae24ce',
    messagingSenderId: '546106504523',
    projectId: 'wasalni-68a0d',
    databaseURL: 'https://wasalni-68a0d-default-rtdb.firebaseio.com',
    storageBucket: 'wasalni-68a0d.firebasestorage.app',
    androidClientId: '546106504523-13ctcomndmu11ev9j47mi1db6s3u1bjj.apps.googleusercontent.com',
    iosClientId: '546106504523-ksrqcjqv2ughvbl0iub6rjr4os5bfsv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.itiMoqaf',
  );

}