const String apiBaseURL = "https://auth-api-4-h4v4.onrender.com";
//final String apiBaseURL = 'http://192.168.1.4:5000';

const String register = "/api/auth/register";
const String login = "/api/auth/login";
const String updateProfile = "/api/auth/update-profile";
const String station = "/api/station";
const String lines = "lines";
const String near = "/api/station/near";
const String vichels = "vichels";
const String verifyEmailEndpoint = "/api/auth/verify-email";
const String posts="/api/community/posts";
const String getUserById = "/api/auth/user";
const String conversations = "/api/conversations";
const String messages = "/api/messages";
const String checkOut= "/api/payment";
const String sendVerificationPassword = "/api/auth/send-verification-password";
const String verifyPassword = "/api/auth/verify-password";
const String resetPassword= "/api/auth/reset-password";
