default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
      sh "flutter clean"
      sh "flutter build apk --release"
      firebase_app_distribution(
        app: "1:671942974107:android:05cadba8b6a6b6ec19443e",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        testers: "abdofekryasda@gmail.com",
        release_notes: "First Fastlane distribute",
        upload_timeout: 20000,
      )
  end
end
